repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-added-large-files
  -   id: check-ast
  -   id: check-case-conflict
  -   id: check-merge-conflict
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.971'
  hooks:
  -   id: mypy
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  -   id: bandit
      exclude: ^(tests/)
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  -   id: black
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  -   id: flake8
